[package]
name = "kanso-gcs"
version.workspace = true
edition.workspace = true

[dependencies]
kanso-client = { workspace = true }
async-trait = { workspace = true }
reqwest = { workspace = true }
gcp_auth = { workspace = true }
serde_json = { workspace = true }
urlencoding = { workspace = true }
